### ISSUE TITLE
Add functionality to start button

### ISSUE THREAD

**Issue by huntermassey33** [ucsb-cs148-f21/project-t04-youtubevoice#28]
Criteria:
Starts the voice changing when clicked

**Comment by notadgupta** [comment]
Please don't assign everyone on a certain task. It does create a bit of confusion on who exactly has to do the work. Since you are the creator of the button, help lead the integration of the button by calling out particular team members along with the skill sets that you require from them and set a meeting time to finish the task.

Thank you!
